/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package semesterproject;

import Classes.*;
import database.Database;
import handler.ShowHandler;
import handler.TicketHandler;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;


public class GUI extends javax.swing.JFrame {

    private Hall hall;
    private TicketHandler tktHandler;

    /**
     * Creates new form Test
     */
    public GUI() {
        //hall = new Hall(14, 20);
        tktHandler = new TicketHandler();
        initComponents();
        addMovies();
        timeBox.setEnabled(false);
    }

    private void addTimes() {
        timeBox.setEnabled(false);

        Show theShow = (Show) movieBox.getSelectedItem();
        ArrayList<String> times = ShowHandler.getInstance().getTimes(theShow);
        for (String time : times) {
            timeBox.addItem(time);
        }

        timeBox.setEnabled(true);
    }

    public void addMovies() {
        movieBox.setEnabled(false);
        movieBox.removeAllItems();
        ArrayList<Show> shows = ShowHandler.getInstance().getShows();
        ShowHandler.getInstance().removeDuplicates(shows);

        for (Show show : shows) {
            movieBox.addItem(show);
        }

        movieBox.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        timeBox = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        movieBox = new javax.swing.JComboBox();
        seatChoiceSal1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel(){
            public void paint(Graphics g) {
                super.paint(g);
                hall.drawSeats(g);
            }
        }
        ;
        ticketTypeBox = new javax.swing.JComboBox();
        payButtonHall1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        payment = new javax.swing.JPanel();
        nameField = new javax.swing.JTextField();
        ageField = new javax.swing.JTextField();
        phoneField = new javax.swing.JTextField();
        PayButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        movieInfo = new javax.swing.JTextArea();
        lastNameField = new javax.swing.JTextField();
        discountBox = new javax.swing.JCheckBox();
        discountField = new javax.swing.JTextField();
        discountButton = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        timeBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tider" }));
        timeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeBoxActionPerformed(evt);
            }
        });

        jButton4.setText("Videre");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/semesterproject/Udklip111.PNG"))); // NOI18N
        jLabel1.setText("jLabel1");

        movieBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movieBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton4)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(movieBox, 0, 344, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(timeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(228, 228, 228))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)
                        .addGap(111, 111, 111)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(timeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(movieBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 129, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4)))
                .addGap(24, 24, 24))
        );

        jPanel1.add(jPanel2, "card2");

        seatChoiceSal1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                seatChoiceSal1MousePressed(evt);
            }
        });

        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );

        ticketTypeBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Billet type", "Voksen billet", "Børne billet", "Pensionist billet" }));

        payButtonHall1.setText("Videre");
        payButtonHall1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButtonHall1ActionPerformed(evt);
            }
        });

        jButton1.setText("Tilbage");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout seatChoiceSal1Layout = new javax.swing.GroupLayout(seatChoiceSal1);
        seatChoiceSal1.setLayout(seatChoiceSal1Layout);
        seatChoiceSal1Layout.setHorizontalGroup(
            seatChoiceSal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seatChoiceSal1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(seatChoiceSal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, seatChoiceSal1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 361, Short.MAX_VALUE)
                        .addComponent(ticketTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(payButtonHall1)))
                .addContainerGap())
        );
        seatChoiceSal1Layout.setVerticalGroup(
            seatChoiceSal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seatChoiceSal1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(seatChoiceSal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(seatChoiceSal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ticketTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(payButtonHall1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, seatChoiceSal1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())))
        );

        jPanel1.add(seatChoiceSal1, "card5");

        nameField.setText("Fornavn");

        ageField.setText("Alder");

        phoneField.setText("tlf Nummer");

        PayButton.setText("Bestil");
        PayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayButtonActionPerformed(evt);
            }
        });

        movieInfo.setColumns(20);
        movieInfo.setRows(5);
        jScrollPane1.setViewportView(movieInfo);

        lastNameField.setText("Efternavn");

        discountBox.setText("Jeg har en rabatkode");
        discountBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountBoxActionPerformed(evt);
            }
        });

        discountField.setEditable(false);

        discountButton.setText("Tilføj");
        discountButton.setEnabled(false);
        discountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountButtonActionPerformed(evt);
            }
        });

        jButton5.setText("Tilbage");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paymentLayout = new javax.swing.GroupLayout(payment);
        payment.setLayout(paymentLayout);
        paymentLayout.setHorizontalGroup(
            paymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paymentLayout.createSequentialGroup()
                        .addGroup(paymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(paymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paymentLayout.createSequentialGroup()
                                .addGap(0, 422, Short.MAX_VALUE)
                                .addComponent(PayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paymentLayout.createSequentialGroup()
                                .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(paymentLayout.createSequentialGroup()
                        .addGroup(paymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(paymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(discountField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(discountBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(discountButton)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        paymentLayout.setVerticalGroup(
            paymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(discountBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(discountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(discountButton)
                .addGap(17, 17, 17)
                .addGroup(paymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        jPanel1.add(payment, "card4");

        jButton3.setText("Tilbage til forsiden");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Vivaldi", 1, 36)); // NOI18N
        jLabel2.setText("Tak for din bestilling, ha en go' tur");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Show show = (Show) movieBox.getSelectedItem();
        String str;
        str = show.getHallNumber();
        switch (str) {
            case "Sal 1": hall = new Hall(14, 20);
                break;
            case "Sal 2": hall = new Hall(8, 12);
                break;
            case "Sal 3": hall = new Hall(8, 6);
                break;
            default:
                break;
        }
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.next(jPanel1);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void PayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayButtonActionPerformed
        boolean customerFail = false;

        if (nameField.getText().matches("[a-zA-Z]+")) {
            nameField.setBorder(null);
            nameField.updateUI();
        } else {
            customerFail = true;
            nameField.setBorder(BorderFactory.createLineBorder(Color.decode("#ff0000")));
        }

        if (lastNameField.getText().matches("[a-zA-Z]+")) {
            lastNameField.setBorder(null);
            lastNameField.updateUI();
        } else {
            customerFail = true;
            lastNameField.setBorder(BorderFactory.createLineBorder(Color.decode("#ff0000")));
        }

        if (ageField.getText().matches("[0-9]+") && ageField.getText().length() <= 3) {
            ageField.setBorder(null);
            ageField.updateUI();
        } else {
            customerFail = true;
            ageField.setBorder(BorderFactory.createLineBorder(Color.decode("#ff0000")));
        }

        if (phoneField.getText().matches("[0-9]+") && phoneField.getText().length() == 8) {
            phoneField.setBorder(null);
            phoneField.updateUI();
        } else {
            customerFail = true;
            phoneField.setBorder(BorderFactory.createLineBorder(Color.decode("#ff0000")));
        }

        CardLayout cl = (CardLayout) jPanel1.getLayout();
        if (!customerFail) {
            cl.next(jPanel1);
        }

    }//GEN-LAST:event_PayButtonActionPerformed

    private void payButtonHall1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payButtonHall1ActionPerformed
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.addLayoutComponent("Payment", payment);
        if (tktHandler.getTickets().size() > 0) {
            cl.show(jPanel1, "Payment");
            movieInfo.setText("Du har bestilt " + tktHandler.getTickets().size() + " billetter\n"
                    + "til filmen .....\n" + "\n" + "Billetter bestilt:  \n" + tktHandler.getTicketTypes()
                    + "\n" + "Samlet pris = " + tktHandler.getTotal() + " kr");
            movieInfo.setEditable(false);
            discountField.setEditable(false);
        }
    }//GEN-LAST:event_payButtonHall1ActionPerformed

    private void movieBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movieBoxActionPerformed
        addTimes();
        //Show selectedShow;
//        if (movieBox.isEnabled()) {
//            selectedShow = (Show) jComboBox1.getSelectedItem();
//            if (selectedShow != null) {
//                jComboBox3.removeAllItems();
//                ArrayList<Show> tempShow = selectedShow.getShow();
//                for (Show show : tempShow) {
//                    jComboBox3.addItem(show);
//                }
//            }
//        }
    }//GEN-LAST:event_movieBoxActionPerformed

    private void seatChoiceSal1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seatChoiceSal1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatChoiceSal1MousePressed

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        String ticketType;
        ticketType = (String) ticketTypeBox.getSelectedItem();
        int seat = hall.translateX(evt.getX());
        int row = hall.translateY(evt.getY());
        Ticket ticket = new Ticket();
        if (seat >= 0 && row >= 0) {
            if (evt.getButton() == 1) {
                if (tktHandler.getTickets().size() == 4) {
                JOptionPane.showMessageDialog(this, tktHandler.getTooManyTickets());
                } else {
                switch (ticketType) {
                    case "Voksen billet":
                        ticket = new TicketAdult();
                        tktHandler.getTickets().add(ticket);
                        hall.bookSeat(row, seat);
                        break;
                    case "Pensionist billet":
                        ticket = new TicketElder();
                        tktHandler.getTickets().add(ticket);
                        hall.bookSeat(row, seat);
                        break;
                    case "Børne billet":
                        ticket = new TicketMinor();
                        tktHandler.getTickets().add(ticket);
                        hall.bookSeat(row, seat);
                        break;
                    default:
                        JOptionPane.showMessageDialog(this, tktHandler.getNoTicketType());
                        break;
                }

            }
            }
            if (evt.getButton() == 3) {
                hall.clearSeat(row, seat);
                tktHandler.getTickets().remove(tktHandler.getTickets().size() - 1);
            }
            
        }
    

    jPanel5.repaint ();

    }//GEN-LAST:event_jPanel5MousePressed

    private void discountBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountBoxActionPerformed
        if (discountBox.isSelected()) {
            discountField.setEditable(true);
            discountButton.setEnabled(true);
        } else {
            discountField.setEditable(false);
            discountButton.setEnabled(false);
        }

    }//GEN-LAST:event_discountBoxActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.addLayoutComponent("start", jPanel2);
        cl.show(jPanel1, "start");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void discountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountButtonActionPerformed
        if (discountField.getText().equalsIgnoreCase(tktHandler.getDiscountCode())) {
            movieInfo.setText("Du har bestilt " + tktHandler.getTickets().size() + " billetter\n"
                    + "til filmen .....\n" + "\n" + "Billetter bestilt:  \n" + tktHandler.getTicketTypes()
                    + "\n" + tktHandler.getDiscountType() + "Samlet pris = " + (int) (tktHandler.getTotal() * 0.80) + " kr");
        }
    }//GEN-LAST:event_discountButtonActionPerformed

    private void timeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeBoxActionPerformed

    }//GEN-LAST:event_timeBoxActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        CardLayout cl = (CardLayout) jPanel1.getLayout();
            cl.previous(jPanel1);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CardLayout cl = (CardLayout) jPanel1.getLayout();
            cl.previous(jPanel1);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PayButton;
    private javax.swing.JTextField ageField;
    private javax.swing.JCheckBox discountBox;
    private javax.swing.JButton discountButton;
    private javax.swing.JTextField discountField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JComboBox<Show> movieBox;
    private javax.swing.JTextArea movieInfo;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton payButtonHall1;
    private javax.swing.JPanel payment;
    private javax.swing.JTextField phoneField;
    private javax.swing.JPanel seatChoiceSal1;
    private javax.swing.JComboBox ticketTypeBox;
    private javax.swing.JComboBox timeBox;
    // End of variables declaration//GEN-END:variables

}
